/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Message.hpp                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: pablo <pablo@student.42.fr>                +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/03/05 22:14:16 by pablo             #+#    #+#             */
/*   Updated: 2026/03/05 22:21:39 by pablo            ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef MESSAGE_HPP
# define MESSAGE_HPP

#include <string> 
#include <stdint.h>     

#define SERVER_NAME "irc.42madrid.com"

/*
Message Class
Represents a complete IRC message, both input (received command)
and output (numeric response or command generated by the server).
An IRC message has this general structure:
[:prefix] <command> <arg1> <arg2> ... [:suffix]
Examples:
PRIVMSG #channel :hello everyone
:nick!user@host JOIN #channel
:server 433 nick
:Nickname is already in use

This class allows you to:

- Parse messages received from the client (parseRequest)
- Construct messages to send to the client (setCommand, setReplyCode, pushArg, pushSuffix)
- Convert the message to a string ready to send (stringify)

*/

class Message
{
private:
    /*
    _prefix
    -------
    Optional part of the message that indicates who is sending the message.

    Example: "nick!user@host"

    Only appears in:

    - Messages sent by the server

    - Messages forwarded to other clients
    */
    std::string _prefix;

    /*
    _command
    Textual IRC command (PRIVMSG, JOIN, NICK, ERROR, MODE...)
    Only used when the message is a request or a server command.

    If the message is a numeric response, it is ignored.

    */
    std::string _command;

    std::string _args[15];

    size_t      _argsCount;

    bool        _isRequest;

    bool        _hasSuffix;

    uint16_t    _replyCode;


public:

    Message ();
    Message(const Message &other); 
    Message &operator=(const Message &other);
    ~Message(); 

    /*
    stringify()
    -----------
    Converts the message into a valid IRC string, without adding "\r\n".
    The server must add it when sending.

    */
    std::string stringify(void) const;

    Message     &setPrefix(const std::string &prefix);

    Message     &pushArg(const std::string &arg);

    Message     &pushSuffix(const std::string &arg);

    Message     &setReplyCode(uint16_t replyCode);

    Message     &setCommand(const std::string &command);

    /*
     Getters
     */

    const std::string   &prefix () const;
    const std::string   &command () const;
    const std::string   &arg (size_t index) const;
    size_t              argsCount () const;
    const std::string   &suffix () const;
    bool                isRequest () const;
    bool                hasSuffix () const;
    uint16_t            replyCode () const;

    /*
    Parses a message received from the client.
    Returns true if the format is valid.
    Example input:
    ":nick!user@host PRIVMSG #channel :hello everyone"
    */
    bool parseRequest(const std::string &str);

	
	std::string getCommand() const;
	const std::string& getArg(int i) const;
	int getArgCount() const;
	std::string getTrailing() const;
	std::string toString() const;
};

#endif
